"""add refunded, challenge_id and unique

Revision ID: 2ab2fc8b9952
Revises: cc831e504342
Create Date: 2026-05-08 23:35:43.637904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ab2fc8b9952'
down_revision: Union[str, Sequence[str], None] = 'cc831e504342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('refunded', sa.Boolean(), nullable=False))
    op.add_column('transactions', sa.Column('challenge_id', sa.String(length=64), nullable=True))
    op.create_unique_constraint('uq_transactions_user_challenge', 'transactions', ['user_id', 'challenge_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_transactions_user_challenge', 'transactions', type_='unique')
    op.drop_column('transactions', 'challenge_id')
    op.drop_column('predictions', 'refunded')
    # ### end Alembic commands ###
