"""Add TimeStampMixin columns to all models

Revision ID: cdff5a23e6ad
Revises: d4e7a3cfe1ca
Create Date: 2026-04-23 11:12:57.198256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdff5a23e6ad'
down_revision: Union[str, Sequence[str], None] = 'd4e7a3cfe1ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('transactions', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('transactions', 'updated_at')
    op.drop_column('predictions', 'updated_at')
    # ### end Alembic commands ###
